export { default as MainHero } from './MainHero/MainHero';
export { default as Founder } from './Founder/Founder';
export { default as Map } from './Map/Map';
export { default as Loyalnost } from './Loyalnost/Loyalnost';
export { default as VideoSection } from './VideoSection/VideoSection';
export { default as Trust } from './Trust/Trust';
export { default as Mission } from './Mission/Mission';
export { default as Statistic } from './Statistic/Statistic';
export { default as Consultation } from './Сonsultation/Сonsultation';
