export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as VdsButton } from './Vds/VdsButton';
export { default as VdsPanel } from './VdsPanel/VdsPanel';
export { default as Button } from './Button/Button';
export { default as Popup } from './Popup/Popup';
export { Form } from './Form/Form';
export { default as MenuButton } from './Menu-button/Menu-button'
export { default as LightForm } from './LightForm/LigthForm';
export { default as SpecialistCard } from './SpecialistCard/SpecialistCard';
export { default as SpecializationCard } from './SpecializationCard/SpecializationCard';
export { default as Breadcrumbs } from './Breadcrumbs/Breadcrumbs';
export { default as SpecialistList } from './SpecialistList/SpecialistList';
export { default as OurWorksList } from './OurWorksList/OurWorksList';
export { default as OurWorksCard } from './OurWorksCard/OurWorksCard';
export { default as LinkButton } from './LinkButton/LinkButton';
export { default as ContentRenderer } from './ContentRenderer/ContentRenderer ';
export { default as Tabs } from './Tabs/Tabs';
export { default as PriceInfo } from './PriceInfo/PriceInfo';
export { default as Document } from './Document/Document';